name: Deploy

on: [push]

jobs:
  lint-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install yarn
        run: |
          npm install yarn -g
      
      - name: Install dependencies
        run: |
          yarn
      
      - name: Lint
        run: |
          yarn next lint

  lint-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          ./api

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache: true
      
      - name: Clippy
        run: cargo clippy -- -W warnings

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          ./api

    needs: [lint-api]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Build
        run: cargo build --release
        
