name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-web:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./web

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install yarn
        run: |
          npm install yarn -g
      
      - name: Install dependencies
        run: |
          yarn
      
      - name: Lint
        run: |
          yarn next lint

  lint-api:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory:
          ./api

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache: true
          cache-workspaces: ./api
      
      - name: Clippy
        run: cargo clippy -- -W warnings
  
  deploy-web:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: ./web

    strategy:
      matrix:
        node-version: [24.x]

    needs: [lint-web]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install yarn
        run: |
          npm install yarn -g
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create .env file
        run: |
          cat <<EOF > .env.production
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_PUBLIC_URL }}
          NEXT_PUBLIC_SITE_NAME=${{ secrets.NEXT_PUBLIC_SITE_NAME }}
          NEXT_PUBLIC_TURNSTILE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_KEY }}
          NEXT_PUBLIC_ADSENSE_PUBLISHER_ID=${{ secrets.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID }}
          NEXT_PUBLIC_COOKIEBOT_API_KEY=${{ secrets.NEXT_PUBLIC_COOKIEBOT_API_KEY }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          NEXT_PUBLIC_PRIVACY_ADMIN_FULL_NAME=${{ secrets.NEXT_PUBLIC_PRIVACY_ADMIN_FULL_NAME }}
          NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL=${{ secrets.NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL }}
          NEXT_PUBLIC_PRIVACY_SITE_URL=${{ secrets.NEXT_PUBLIC_PRIVACY_SITE_URL }}
          EOF
      
      - name: Build app
        run: yarn build

      - name: Archive build
        run: |
          tar -czf web.tar.gz .next public package.json yarn.lock

      - name: Upload archive to the server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          scp -i private_key -o StrictHostKeyChecking=no web.tar.gz $VPS_USER@$VPS_HOST:/home/mz-prod/web/web.tar.gz

      - name: Extract and restart web
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /home/mz-prod/web/
            rm -rf ./.next
            rm -rf ./public
            rm -rf ./package.json
            rm -rf ./yarn.lock
            
            tar -xzf ./web.tar.gz -C ./
            yarn install --production

            screen -S web -X stuff "^C"
            sleep 1

            screen -S web -X stuff "clear\n"
            screen -S web -X stuff "yarn start\n"
          EOF

  deploy-api:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory:
          ./api

    needs: [lint-api]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          cache-workspaces: ./api

      - name: Build
        run: cargo build --release

      - name: Stop API
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
  
          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            screen -S api -X stuff "^C"
            sleep 1
          EOF

      - name: Upload binary to remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          scp -i private_key -o StrictHostKeyChecking=no target/release/api $VPS_USER@$VPS_HOST:/home/mz-prod/api
        
      - name: Start API
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
  
          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /home/mz-prod/api
            chmod +x ./api
  
            screen -S api -X stuff "clear\n"
            screen -S api -X stuff "./api\n"
          EOF
