name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-web:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.9"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run --cwd apps/web lint

  lint-api:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.9"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run --cwd apps/api tsc --noEmit

  deploy-web:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    needs: [lint-web, deploy-api]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.9"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create .env file
        working-directory: ./apps/web
        run: |
          cat <<EOF > .env.production
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_PUBLIC_URL }}
          NEXT_PUBLIC_SITE_NAME=${{ secrets.NEXT_PUBLIC_SITE_NAME }}
          NEXT_PUBLIC_TURNSTILE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_KEY }}
          NEXT_PUBLIC_ADSENSE_PUBLISHER_ID=${{ secrets.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID }}
          NEXT_PUBLIC_COOKIEBOT_API_KEY=${{ secrets.NEXT_PUBLIC_COOKIEBOT_API_KEY }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          NEXT_PUBLIC_PRIVACY_ADMIN_FULL_NAME=${{ secrets.NEXT_PUBLIC_PRIVACY_ADMIN_FULL_NAME }}
          NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL=${{ secrets.NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL }}
          NEXT_PUBLIC_PRIVACY_SITE_URL=${{ secrets.NEXT_PUBLIC_PRIVACY_SITE_URL }}
          NEXT_PUBLIC_MAP_TILE_STYLES_URL=${{ secrets.NEXT_PUBLIC_MAP_TILE_STYLES_URL }}
          EOF

      - name: Build app
        working-directory: ./apps/web
        run: bun run build

      - name: Archive build
        working-directory: ./apps/web
        run: |
          cp -r public .next/standalone/apps/web/public
          cp -r .next/static .next/standalone/apps/web/.next/static
          tar -czf web.tar.gz -C .next/standalone/apps/web .

      - name: Upload archive to the server
        working-directory: ./apps/web
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          scp -i private_key -o StrictHostKeyChecking=no web.tar.gz $VPS_USER@$VPS_HOST:/home/mz-prod/web/web.tar.gz

      - name: Extract and restart web server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /home/mz-prod/web/
            rm -rf .next public server.js package.json node_modules

            tar -xzf ./web.tar.gz -C ./
            rm web.tar.gz

            screen -S web -X stuff "^C"
            sleep 1

            screen -S web -X stuff "clear\n"
            screen -S web -X stuff "node server.js\n"
          EOF

  deploy-api:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    needs: [lint-api]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Archive build
        working-directory: ./apps/api
        run: |
          zip -r ../../api.zip src package.json tsconfig.json bun.lock drizzle.config.ts

      - name: Upload archive to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          scp -i private_key -o StrictHostKeyChecking=no api.zip $VPS_USER@$VPS_HOST:/home/mz-prod/api.zip

      - name: Deploy and restart API
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /home/mz-prod

            screen -S api -X stuff "^C"
            sleep 1

            rm -rf api/src api/package.json api/tsconfig.json api/bun.lock api/drizzle.config.ts api/node_modules
            unzip -o api.zip -d api
            rm api.zip

            cd api
            bun install

            screen -S api -X stuff "clear\n"
            screen -S api -X stuff "bun run start\n"
          EOF
